"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import{useDispatch} from "react-redux";
import ReduxProvider from "@/components/ReduxProvider";
import { useEffect } from "react";
import { loadFromStorage } from "@/store/authSlice";
import { Analytics } from "@vercel/analytics/next"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


function AppContent({ children }: { children: React.ReactNode }) {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(loadFromStorage());
  }, [dispatch]);

  return (
    <div>
     
      <main className="min-h-screen bg-gray-50">
        {children}
      </main>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/logo.ico" />
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <AppContent>
            {children}
               <Analytics />
            </AppContent>
        </ReduxProvider>
      </body>
    </html>
  );
}
